name: restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  go_router: ^8.2.0
  google_maps_flutter: ^2.2.6
  http: ^1.0.0
  image_picker: ^1.0.1
  json_annotation: ^4.8.1
  location: ^4.4.0
  shared_preferences: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
